// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// expand_interval_data
Rcpp::List expand_interval_data(Rcpp::DataFrame key, Rcpp::DataFrame interval);
RcppExport SEXP rplexos_expand_interval_data(SEXP keySEXP, SEXP intervalSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::DataFrame >::type key(keySEXP );
        Rcpp::traits::input_parameter< Rcpp::DataFrame >::type interval(intervalSEXP );
        Rcpp::List __result = expand_interval_data(key, interval);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// expand_tkey
Rcpp::DataFrame expand_tkey(Rcpp::DataFrame tkey);
RcppExport SEXP rplexos_expand_tkey(SEXP tkeySEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::DataFrame >::type tkey(tkeySEXP );
        Rcpp::DataFrame __result = expand_tkey(tkey);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// process_xml
Rcpp::List process_xml(std::string xml);
RcppExport SEXP rplexos_process_xml(SEXP xmlSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< std::string >::type xml(xmlSEXP );
        Rcpp::List __result = process_xml(xml);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
