# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

expand_interval_data <- function(key, interval) {
    .Call('rplexos_expand_interval_data', PACKAGE = 'rplexos', key, interval)
}

expand_tkey <- function(tkey) {
    .Call('rplexos_expand_tkey', PACKAGE = 'rplexos', tkey)
}

new_database <- function(db_file, xml) {
    .Call('rplexos_new_database', PACKAGE = 'rplexos', db_file, xml)
}

